Arc-570: Tab focus bug fix / 404 routing / styling linting
* Removed keyboard logic that was sending focus to skiplink when using keyboard

* added 404 page

* updated pre commit to ensure md files are parsed before commiting

* added pre commit linter to catch css issues before committing

* fix: a couple styles, linting issues, and about-us page routing

---------

Co-authored-by: silverli <lindsaysilver1@gmail.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,3 +3,25 @@
 
 echo "🔍 Running tests before commit..."
 npm test -- --watchAll=false --silent
+
+echo "📄 Parsing markdown files..."
+npm run parse-md-files
+
+echo "🔍 Checking for changes after parsing markdown files..."
+if ! git diff --quiet; then
+  echo "❌ Changes detected after running parse-md-files. Please commit the updated files."
+  exit 1
+fi
+
+echo "✅ No changes detected. Moving on..."
+
+echo "🔍 Running SCSS lint check..."
+npm run lint:scss
+if [ $? -ne 0 ]; then
+  echo "❌ SCSS linting failed. Please fix the errors before committing."
+  exit 1
+fi
+
+echo "✅ All checks passed. Proceeding with the commit..."
+
+
